"""
Django settings for pgdi project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import os
import ldap

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g6!^5&2)i%b0ma9g&(4$5x9#y@t_yd#vy%&9zx!n+c7+#)w4rk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
)

# ldap authentication

from django_auth_ldap.config import LDAPSearch, PosixGroupType

AUTH_LDAP_SERVER_URI = "ldap://pgdi:389"
AUTH_LDAP_BIND_DN = "cn=admin,dc=pgdi,dc=inf"
AUTH_LDAP_BIND_PASSWORD = "toor"

AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=usuarios,dc=pgdi,dc=inf",
    ldap.SCOPE_SUBTREE, "(uid=%(user)s)")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("ou=grupos,dc=pgdi,dc=inf",
    ldap.SCOPE_SUBTREE, "(objectClass=PosixGroup)"
)

AUTH_LDAP_GROUP_TYPE = PosixGroupType(name_attr="cn")
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "cn=activos,ou=roles,ou=grupos,dc=pgdi,dc=inf",
    "is_staff": "cn=profesores,ou=roles,ou=grupos,dc=pgdi,dc=inf",
    "is_superuser": "cn=administradores,ou=roles,ou=grupos,dc=pgdi,dc=inf"
}

AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}

# ldap for pgdi

LDAP_VERSION = ldap.VERSION3
LDAP_SERVER_NAME = "pgdi"

LDAP_DOMAIN_BASE = "dc=pgdi,dc=inf"
LDAP_USERS_BASE = "ou=usuarios," + LDAP_DOMAIN_BASE
LDAP_STUDENTS_BASE = "ou=alumnos," + LDAP_USERS_BASE
LDAP_TEACHERS_BASE = "ou=profesores," + LDAP_USERS_BASE
LDAP_EXSTUDENTS_BASE = "ou=exalumnos," + LDAP_USERS_BASE
LDAP_GROUPS_BASE = "ou=grupos," + LDAP_DOMAIN_BASE
LDAP_ROLES_BASE = "ou=roles," + LDAP_GROUPS_BASE
LDAP_GRADES_BASE = "ou=grados," + LDAP_GROUPS_BASE
LDAP_OS_BASE = "ou=so," + LDAP_GROUPS_BASE

# smtp config

SMTP_HOST = 'smtp.gmail.com'
SMTP_USER = 'smtp.segundo.asir@gmail.com'
SMTP_PASS = 'pass.segundo.asir'
SMTP_NAME = 'Robot PGDI'

# PGDI
# Valores por defecto para los nuevos usuarios

LOGIN_SHELL = '/bin/bash'
HOME_DIRECTORY = '/home/pub/'

# Numero de directorios de gran peso a mostrar
MAX_SIZE_FILE_LIMIT = 10

# Umbrales de alerta para disco ocupado (en %)
QUOTA_WARN1_LEVEL = 60
QUOTA_WARN2_LEVEL = 90

# Campos de "repquota"
QUOTA_USED_DISK_FIELD = 3
QUOTA_SOFT_LIMIT_FIELD = 4
QUOTA_HARD_LIMIT_FIELD = 5


# Application definition

INSTALLED_APPS = [
    'suit',
    'pgdiapp.apps.PgdiappConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pgdi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pgdi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'pgdi',
        'USER': 'pgdiuser',
        'PASSWORD': 'pgdipass',
        'HOST': 'pgdi',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django Suit configuration

SUIT_CONFIG = {
    'ADMIN_NAME': 'Admin. PGDI',
}

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'CET'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SHELL_PLUS = "ipython"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
